### ISSUE TITLE
Tutorial Map Bug

### ISSUE THREAD

**Issue by Blasterott18** [turtlewit/GSHS_RPG#10]
When using the map (typing "map") on the beginning area, the map, rather than normally showing one "P" and 2 "t"s, as the map is 3 tiles long and the player is inhabiting one space, the tiles on the map repeat 8 times.

It looks like the following, given that the player has no moved:
PPPPPPPPP
ttttttttt
ttttttttt

**Comment by turtlewit** [comment]
Fixed in master. Closed.
