### ISSUE TITLE
Blocked Movement Message Bug

### ISSUE THREAD

**Issue by Blasterott18** [turtlewit/GSHS_RPG#12]
When you attempt to move where you cannot move, the message that shows up telling you that you cannot go there is split at the middle, only showing the latter half of the message.

Example: Attempting to walk out of bounds in the Tutorial world displays "h. There is a light force preventing you from stepping outside the walkway."

The intended result is to display "A void encompasses every direction but south. There is a light force preventing you from stepping outside the walkway."

**Comment by turtlewit** [comment]
Fixed in commit 6542838 (render-cleanup). Leaving open because branch is incomplete.
